export const FETCH_COUNTRY_DATA_INIT_ACTION = "FETCH_COUNTRY_DATA_INIT_ACTION";
export const FETCH_COUNTRY_DATA_SUCCESS_ACTION =
  FETCH_COUNTRY_DATA_INIT_ACTION + "_SUCCESS";
export const FETCH_COUNTRY_DATA_FAIL_ACTION =
  FETCH_COUNTRY_DATA_INIT_ACTION + "_ERROR";
